# 项目自定义属性设置
okya:
  # 名称
  name: OKYA
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2023
  # 文件上传目录（注意Linux和Windows上的目录结构不同）
  fileFolder: /home/uploadFile/
  # 上传的图标文件内部url
  iconUrlPrefix: https://okya.top/file
  # 验证码类型 math 数字计算 char 字符验证 none不启用验证码
  captchaType: math

server:
  port: 11001
  tomcat:
    max-http-form-post-size: 20MB
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

pagehelper:
  # 是否启用分页合理化。
  # 如果启用，当pagenum<1时，会自动查询第一页的数据，当pagenum>pages时，自动查询最后一页数据；
  # 不启用的，以上两种情况都会返回空数据
  reasonable: false
  # 默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  supportMethodsArguments: true
  # 用于从对象中根据属性名取值，
  # 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值，
  # 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  params: count=countSql

logging:
  config: classpath:logback.xml

spring:
  servlet:
    multipart:
      # 最大上传单个文件大小：默认1M  如果改为-1说明无大小限制
      max-file-size: 5MB
      # 最大总上传的数据大小:默认10M(对同时上传多个文件大小的限制） 如果改为-1说明无大小限制
      max-request-size: 50MB
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  async:
    # 核心线程池大小
    corePoolSize: 50
    # 最大可创建的线程数
    maxPoolSize: 200
    # 队列最大长度
    queueCapacity: 1000
    # 线程池维护线程所允许的空闲时间
    keepAliveSeconds: 300
  # 接口地址前缀（默认需要鉴权）
  api:
    path:
      # 测试接口地址前缀
      test-prefix: /test
      # 不需要鉴权接口地址前缀
      unAuth-prefix: /ua

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

wx:
  # 小程序appId/appSecret/
  appId: 123
  appSecret: 321
  # 获取小程序全局唯一后台接口调用凭据
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token
  unlimitedQRCode: https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=

security:
  token:
    # 过期时间（分钟）
    expireTime: 60
    # 请求头内的位置
    header: Authorization
    # 前缀
    prefix: Bearer
    # 秘钥
    secret: 0kyatopToken
    # 用户信息键
    userKey: USER_KEY
  # 防篡改、防重放攻击、防重复提交
  sign:
    # 签名验证超时时间（毫秒）
    timeout: 60000
    # 请求头内的位置
    signHeader: Sign
    timeHeader: Timestamp
    # 测试时加上/*所有请求全部不校验
    ignoreUri:
      # - /*
      - /error403
      - /error401
      - /getQRCodeState
      - /loginQRCode
      - /captchaImage
      - /druid/*
      - /uploader/chunk
    repeatMillis: 5000
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# MyBatis配置
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml

# prefix、pattern
sequence:
  list:
    - key: ORDER
      length: 3
      initialValue: 0
      minValue: 0
      maxValue: 999
      step: 1
      circle: true
      updateInterval: DAY
    - key: PAYCODE
      prefix: 320600
      pattern: "yy"
      length: 12
      initialValue: 600000000000
      minValue: 600000000000
      maxValue: 600100000000
      step: 1
      circle: true
      updateInterval: YEAR
